### ISSUE TITLE
convert kivy to apk file

### ISSUE THREAD

**Issue by haikal000** [wishrohitv/google-colab-for-kivy#3]
I have a problem converting my code which is a project related to AI project (.h5 file). I think it maybe related with the application requirements like tensorflow,numpy and etc. I have placed my training AI model(.h5) and the app code (.py). Please help me for my final year project.
[project.zip](https://github.com/wishrohitv/google-colab-for-kivy/files/13771822/project.zip)

**Comment by wishrohitv** [comment]
> I have a problem converting my code which is a project related to AI project (.h5 file). I think it maybe related with the application requirements like tensorflow,numpy and etc. I have placed my training AI model(.h5) and the app code (.py). Please help me for my final year project.
> [project.zip](https://github.com/wishrohitv/google-colab-for-kivy/files/13771822/project.zip)
> 

Well I haven't used tensorflow with kivy or in reallife, but yeah it's possible to use tensorflow with kivy here is example - https://github.com/tito/experiment-tensorflow-lite

**Comment by wishrohitv** [comment]
You can get help from kivy official discord - https://discord.com/invite/rUB9WHD45T

Kivy core developer may tell you
